/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DataFilter {
  'states' : [] | [Array<string>],
  'startYear' : [] | [bigint],
  'endYear' : [] | [bigint],
  'vehicleTypes' : [] | [Array<VehicleType>],
}
export interface Guideline {
  'id' : bigint,
  'title' : string,
  'tips' : Array<string>,
  'description' : string,
  'category' : string,
}
export interface StateStats {
  'yearlyBreakdown' : Array<YearlyStats>,
  'injuries' : bigint,
  'deaths' : bigint,
  'state' : string,
  'totalAccidents' : bigint,
}
export interface SummaryStats {
  'injuries' : bigint,
  'deaths' : bigint,
  'fatalityRate' : bigint,
  'injuryRate' : bigint,
  'totalAccidents' : bigint,
}
export type VehicleType = { 'Car' : null } |
  { 'TwoWheeler' : null } |
  { 'Other' : null } |
  { 'HeavyVehicle' : null };
export interface VehicleTypeStats {
  'vehicleType' : VehicleType,
  'yearlyBreakdown' : Array<YearlyStats>,
  'injuries' : bigint,
  'deaths' : bigint,
  'totalAccidents' : bigint,
}
export interface YearlyStats {
  'year' : bigint,
  'injuries' : bigint,
  'deaths' : bigint,
  'totalAccidents' : bigint,
}
export interface _SERVICE {
  'getAccidentsByState' : ActorMethod<[Array<string>], Array<StateStats>>,
  'getAccidentsByVehicleType' : ActorMethod<
    [Array<VehicleType>],
    Array<VehicleTypeStats>
  >,
  'getAccidentsByYear' : ActorMethod<[bigint, bigint], Array<YearlyStats>>,
  'getAllStates' : ActorMethod<[], Array<string>>,
  'getPreventionGuidelines' : ActorMethod<[], Array<Guideline>>,
  'getSummaryStats' : ActorMethod<[DataFilter], SummaryStats>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];