/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const YearlyStats = IDL.Record({
  'year' : IDL.Nat,
  'injuries' : IDL.Nat,
  'deaths' : IDL.Nat,
  'totalAccidents' : IDL.Nat,
});
export const StateStats = IDL.Record({
  'yearlyBreakdown' : IDL.Vec(YearlyStats),
  'injuries' : IDL.Nat,
  'deaths' : IDL.Nat,
  'state' : IDL.Text,
  'totalAccidents' : IDL.Nat,
});
export const VehicleType = IDL.Variant({
  'Car' : IDL.Null,
  'TwoWheeler' : IDL.Null,
  'Other' : IDL.Null,
  'HeavyVehicle' : IDL.Null,
});
export const VehicleTypeStats = IDL.Record({
  'vehicleType' : VehicleType,
  'yearlyBreakdown' : IDL.Vec(YearlyStats),
  'injuries' : IDL.Nat,
  'deaths' : IDL.Nat,
  'totalAccidents' : IDL.Nat,
});
export const Guideline = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tips' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const DataFilter = IDL.Record({
  'states' : IDL.Opt(IDL.Vec(IDL.Text)),
  'startYear' : IDL.Opt(IDL.Nat),
  'endYear' : IDL.Opt(IDL.Nat),
  'vehicleTypes' : IDL.Opt(IDL.Vec(VehicleType)),
});
export const SummaryStats = IDL.Record({
  'injuries' : IDL.Nat,
  'deaths' : IDL.Nat,
  'fatalityRate' : IDL.Nat,
  'injuryRate' : IDL.Nat,
  'totalAccidents' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAccidentsByState' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(StateStats)],
      ['query'],
    ),
  'getAccidentsByVehicleType' : IDL.Func(
      [IDL.Vec(VehicleType)],
      [IDL.Vec(VehicleTypeStats)],
      ['query'],
    ),
  'getAccidentsByYear' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(YearlyStats)],
      ['query'],
    ),
  'getAllStates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPreventionGuidelines' : IDL.Func([], [IDL.Vec(Guideline)], ['query']),
  'getSummaryStats' : IDL.Func([DataFilter], [SummaryStats], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const YearlyStats = IDL.Record({
    'year' : IDL.Nat,
    'injuries' : IDL.Nat,
    'deaths' : IDL.Nat,
    'totalAccidents' : IDL.Nat,
  });
  const StateStats = IDL.Record({
    'yearlyBreakdown' : IDL.Vec(YearlyStats),
    'injuries' : IDL.Nat,
    'deaths' : IDL.Nat,
    'state' : IDL.Text,
    'totalAccidents' : IDL.Nat,
  });
  const VehicleType = IDL.Variant({
    'Car' : IDL.Null,
    'TwoWheeler' : IDL.Null,
    'Other' : IDL.Null,
    'HeavyVehicle' : IDL.Null,
  });
  const VehicleTypeStats = IDL.Record({
    'vehicleType' : VehicleType,
    'yearlyBreakdown' : IDL.Vec(YearlyStats),
    'injuries' : IDL.Nat,
    'deaths' : IDL.Nat,
    'totalAccidents' : IDL.Nat,
  });
  const Guideline = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tips' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const DataFilter = IDL.Record({
    'states' : IDL.Opt(IDL.Vec(IDL.Text)),
    'startYear' : IDL.Opt(IDL.Nat),
    'endYear' : IDL.Opt(IDL.Nat),
    'vehicleTypes' : IDL.Opt(IDL.Vec(VehicleType)),
  });
  const SummaryStats = IDL.Record({
    'injuries' : IDL.Nat,
    'deaths' : IDL.Nat,
    'fatalityRate' : IDL.Nat,
    'injuryRate' : IDL.Nat,
    'totalAccidents' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAccidentsByState' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(StateStats)],
        ['query'],
      ),
    'getAccidentsByVehicleType' : IDL.Func(
        [IDL.Vec(VehicleType)],
        [IDL.Vec(VehicleTypeStats)],
        ['query'],
      ),
    'getAccidentsByYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(YearlyStats)],
        ['query'],
      ),
    'getAllStates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPreventionGuidelines' : IDL.Func([], [IDL.Vec(Guideline)], ['query']),
    'getSummaryStats' : IDL.Func([DataFilter], [SummaryStats], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };