/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DataFilter {
    states?: Array<string>;
    startYear?: bigint;
    endYear?: bigint;
    vehicleTypes?: Array<VehicleType>;
}
export interface SummaryStats {
    injuries: bigint;
    deaths: bigint;
    fatalityRate: bigint;
    injuryRate: bigint;
    totalAccidents: bigint;
}
export interface VehicleTypeStats {
    vehicleType: VehicleType;
    yearlyBreakdown: Array<YearlyStats>;
    injuries: bigint;
    deaths: bigint;
    totalAccidents: bigint;
}
export interface YearlyStats {
    year: bigint;
    injuries: bigint;
    deaths: bigint;
    totalAccidents: bigint;
}
export interface StateStats {
    yearlyBreakdown: Array<YearlyStats>;
    injuries: bigint;
    deaths: bigint;
    state: string;
    totalAccidents: bigint;
}
export interface Guideline {
    id: bigint;
    title: string;
    tips: Array<string>;
    description: string;
    category: string;
}
export enum VehicleType {
    Car = "Car",
    TwoWheeler = "TwoWheeler",
    Other = "Other",
    HeavyVehicle = "HeavyVehicle"
}
export interface backendInterface {
    getAccidentsByState(states: Array<string>): Promise<Array<StateStats>>;
    getAccidentsByVehicleType(vehicleTypes: Array<VehicleType>): Promise<Array<VehicleTypeStats>>;
    getAccidentsByYear(startYear: bigint, endYear: bigint): Promise<Array<YearlyStats>>;
    getAllStates(): Promise<Array<string>>;
    getPreventionGuidelines(): Promise<Array<Guideline>>;
    getSummaryStats(filter: DataFilter): Promise<SummaryStats>;
}
import type { DataFilter as _DataFilter, VehicleType as _VehicleType, VehicleTypeStats as _VehicleTypeStats, YearlyStats as _YearlyStats } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAccidentsByState(arg0: Array<string>): Promise<Array<StateStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccidentsByState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccidentsByState(arg0);
            return result;
        }
    }
    async getAccidentsByVehicleType(arg0: Array<VehicleType>): Promise<Array<VehicleTypeStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccidentsByVehicleType(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccidentsByVehicleType(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccidentsByYear(arg0: bigint, arg1: bigint): Promise<Array<YearlyStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccidentsByYear(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccidentsByYear(arg0, arg1);
            return result;
        }
    }
    async getAllStates(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStates();
            return result;
        }
    }
    async getPreventionGuidelines(): Promise<Array<Guideline>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreventionGuidelines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreventionGuidelines();
            return result;
        }
    }
    async getSummaryStats(arg0: DataFilter): Promise<SummaryStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummaryStats(to_candid_DataFilter_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummaryStats(to_candid_DataFilter_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_VehicleTypeStats_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleTypeStats): VehicleTypeStats {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vehicleType: _VehicleType;
    yearlyBreakdown: Array<_YearlyStats>;
    injuries: bigint;
    deaths: bigint;
    totalAccidents: bigint;
}): {
    vehicleType: VehicleType;
    yearlyBreakdown: Array<YearlyStats>;
    injuries: bigint;
    deaths: bigint;
    totalAccidents: bigint;
} {
    return {
        vehicleType: from_candid_VehicleType_n7(_uploadFile, _downloadFile, value.vehicleType),
        yearlyBreakdown: value.yearlyBreakdown,
        injuries: value.injuries,
        deaths: value.deaths,
        totalAccidents: value.totalAccidents
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Car: null;
} | {
    TwoWheeler: null;
} | {
    Other: null;
} | {
    HeavyVehicle: null;
}): VehicleType {
    return "Car" in value ? VehicleType.Car : "TwoWheeler" in value ? VehicleType.TwoWheeler : "Other" in value ? VehicleType.Other : "HeavyVehicle" in value ? VehicleType.HeavyVehicle : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VehicleTypeStats>): Array<VehicleTypeStats> {
    return value.map((x)=>from_candid_VehicleTypeStats_n5(_uploadFile, _downloadFile, x));
}
function to_candid_DataFilter_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DataFilter): _DataFilter {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    states?: Array<string>;
    startYear?: bigint;
    endYear?: bigint;
    vehicleTypes?: Array<VehicleType>;
}): {
    states: [] | [Array<string>];
    startYear: [] | [bigint];
    endYear: [] | [bigint];
    vehicleTypes: [] | [Array<_VehicleType>];
} {
    return {
        states: value.states ? candid_some(value.states) : candid_none(),
        startYear: value.startYear ? candid_some(value.startYear) : candid_none(),
        endYear: value.endYear ? candid_some(value.endYear) : candid_none(),
        vehicleTypes: value.vehicleTypes ? candid_some(to_candid_vec_n1(_uploadFile, _downloadFile, value.vehicleTypes)) : candid_none()
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    Car: null;
} | {
    TwoWheeler: null;
} | {
    Other: null;
} | {
    HeavyVehicle: null;
} {
    return value == VehicleType.Car ? {
        Car: null
    } : value == VehicleType.TwoWheeler ? {
        TwoWheeler: null
    } : value == VehicleType.Other ? {
        Other: null
    } : value == VehicleType.HeavyVehicle ? {
        HeavyVehicle: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<VehicleType>): Array<_VehicleType> {
    return value.map((x)=>to_candid_VehicleType_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
